# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM - Publish Package

on:
  release:
    types: [created]

# on:
#   push:
#     branches:
#       - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install -g pnpm
          npm install -g newman
          pnpm install
          pnpm test

  Publish:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Update version in constants
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'src/commands/constants.js'
          search-text: '{x.x.x}'
          replacement-text: ${{steps.get_version.outputs.version-without-v}}
      - run: |
          echo "Preparing to publish git-friendly-postman@${NPM_VERSION}"
          npm install -g pnpm
          pnpm version --force --git-tag-version false --commit-hooks false $NPM_VERSION
          pnpm install
          pnpm publish
        env:
          NPM_VERSION: ${{steps.get_version.outputs.version-without-v}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
